apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodapp
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prodapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prodapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prodapp
  namespace: prodapp
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: prodapp
